# **UAS MATA KULIAH ANALITIKA MEDIA SOSIAL**

Nama : Muhammad Bintang Ardiansyah <br />
NIM  : A11.2019.11907

### Topik : Klasifikasi Text
### Objek : Klasifikasi Text pada Email Spam Menggunakan Naive Bayes
<br />

Latar Belakang Masalah : <br/>
Email spam adalah pesan email yang tidak diinginkan atau tidak diminta yang dikirim secara massal ke banyak orang. Spam email biasanya berisi iklan yang tidak diinginkan atau berisi tautan ke situs web yang meragukan. Spam email juga dapat berisi virus atau malware yang dapat merusak komputer pengguna. Masalah utama dengan spam email adalah bahwa ia dapat menyebabkan penumpukan email yang tidak diinginkan pada kotak masuk pengguna, yang dapat menghambat produktivitas dan mengganggu kemampuan untuk menemukan email yang penting. Selain itu, spam email juga dapat menyebabkan keprihatinan keamanan karena pengguna mungkin tergiur untuk mengklik tautan yang tidak aman atau memberikan informasi pribadi kepada pengirim spam yang tidak dapat dipercaya.
Dari masalah tersebut, dibuatlah eksperimen untuk klasifikasi email yang termasuk spam
<br />

Metode : <br />
Klasifikasi Text pada email spam menggunakan Random Forest Classifier

### **Import library yang akan digunakan**

In [2]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

### **Import dataset**

In [11]:
df = pd.read_csv("emails.csv")
df.head(5)
df.isnull().sum()
df.describe()
df.corr()

,the,to,ect,and,for,of,a,you,hou,in,...,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry,Prediction
the,1.000000,0.852715,0.337249,0.841200,0.784112,0.796397,0.784451,0.471392,0.303621,0.845670,...,0.008926,0.075479,0.225586,0.223426,0.101768,0.129466,0.127019,0.341878,0.051021,-0.004421
to,0.852715,1.000000,0.375480,0.825474,0.781971,0.752722,0.896466,0.508513,0.347993,0.881759,...,0.013250,0.101247,0.232847,0.255793,0.093322,0.091639,0.120059,0.406666,0.071388,0.055277
ect,0.337249,0.375480,1.000000,0.272863,0.369777,0.178028,0.400009,0.155783,0.974152,0.298387,...,0.134339,0.031431,0.046080,0.061550,0.004393,-0.007690,0.004368,0.141460,0.002492,-0.120782
and,0.841200,0.825474,0.272863,1.000000,0.751287,0.809665,0.815196,0.476764,0.235953,0.874276,...,0.005151,0.104454,0.272963,0.253440,0.151980,0.084147,0.124766,0.400225,0.042484,0.114364
for,0.784112,0.781971,0.369777,0.751287,1.000000,0.681457,0.744098,0.495852,0.329051,0.762659,...,0.022168,0.041775,0.236213,0.213631,0.134469,0.067151,0.121057,0.301074,0.038126,-0.003101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
military,0.129466,0.091639,-0.007690,0.084147,0.067151,0.073004,0.111685,0.006498,0.005429,0.120620,...,-0.002249,-0.002979,0.043408,0.104297,0.041300,1.000000,0.055227,0.049524,0.010835,0.064850
allowing,0.127019,0.120059,0.004368,0.124766,0.121057,0.108786,0.105358,0.082757,-0.000966,0.138099,...,-0.002675,-0.003543,-0.005130,0.018550,0.276001,0.055227,1.000000,0.096212,-0.003995,0.011279
ff,0.341878,0.406666,0.141460,0.400225,0.301074,0.444252,0.464473,0.195058,0.114210,0.448303,...,0.005403,0.073690,0.130356,0.164296,0.114092,0.049524,0.096212,1.000000,0.049690,0.135479
dry,0.051021,0.071388,0.002492,0.042484,0.038126,0.026403,0.093822,0.028883,0.000601,0.077751,...,-0.003373,0.035028,-0.006468,0.018939,-0.003137,0.010835,-0.003995,0.049690,1.000000,-0.006260
Prediction,-0.004421,0.055277,-0.120782,0.114364,-0.003101,0.197234,0.107776,0.130293,-0.128340,0.154055,...,-0.030375,-0.031694,0.098775,0.064315,0.038161,0.064850,0.011279,0.135479,-0.006260,1.000000

## **Membuat Model NB**

Dalam proyek ini, kami mengklasifikasikan surat yang diketik oleh pengguna sebagai 'Spam' atau 'Bukan Spam'. Dataset asli kami adalah folder dengan 5172 file teks yang berisi email.

Sekarang mari kita mengerti mengapa kita memisahkan kata-kata dari email. Hal ini karena ini adalah masalah pengklasifikasian teks. Ketika sebuah pengklasifikasi spam melihat sebuah email, ia mencari kata-kata potensial yang telah dilihat pada email spam sebelumnya. Jika ia menemukan sebagian besar kata-kata tersebut, maka ia mengelabelnya sebagai 'Spam'. Mengapa saya mengatakan sebagian besar? -->
<br />
<br />
KASUS 1: misalnya mari kita ambil kata 'Greetings'. Misal, itu termasuk di email 'Spam' dan 'Bukan Spam'.
<br/>
KASUS 2: Mari kita pertimbangkan kata 'lottery'. Misal, hanya termasuk di email 'Spam
<br/>
KASUS 3: Mari kita pertimbangkan kata 'murah'. Misal, hanya termasuk di spam.
<br/>
<br/>
Jika sekarang kita mendapatkan email tes, dan itu berisi ketiga kata di atas, ada kemungkinan tinggi bahwa itu adalah email 'Spam'.

Algoritma yang paling efektif untuk masalah pengklasifikasian teks adalah algoritma Naive Bayes, yang bekerja pada teorema Bayes klasik. Teorema ini bekerja pada setiap kata individu dalam data tes untuk membuat prediksi (probabilitas kondisional dengan probabilitas yang lebih tinggi adalah hasil yang diprediksi).

Katakanlah email tes kami (S) adalah, "Anda telah memenangkan sebuah lottery"

BAGAMANA NAIVE BAYES BEKERJA PADA DATA INI -->

P(S) = P('You') P('have') P('won') P('a') P('lottery') __ 1

Oleh Karena itu, P(S|Spam) = P('You'|Spam) P('have'|Spam) P('won'|Spam) P('a'|Spam) P('lottery'|Spam) __ 2

Perhitungan yang sama untuk P (S | Bukan_Spam) __ 3

Jika 2> 3, maka 'Spam' Jika tidak, 'Bukan_Spam'.

APA JIKA PROBALITASNYA NOL? Inilah konsep Lapisan Penyamaran, di mana P (kata-kata) = (jumlah kata + 1) / (jumlah total kata + jumlah kata unik)

Di sini, eksperimen dilakukan pada pengklasifikasi Naive Bayes Multinomial yang ada (di bawah scikit-learn). Untuk memahami lebih lanjut bagaimana Naive Bayes bekerja dengan baik untuk pengklasifikasian teks, akan digunakan klasifikator standar lainnya, SVC, untuk melihat bagaimana kinerja kedua model.

APAKAH MODEL ENSEMBLE AKAN BEKERJA LEBIH BAIK? Marilah kita lihat. Kami akan menggunakan Random Forests untuk membandingkan.

In [12]:
X = df.iloc[:,1:3001]
X

,the,to,ect,and,for,of,a,you,hou,in,...,enhancements,connevey,jay,valued,lay,infrastructure,military,allowing,ff,dry
0,0,0,1,0,0,0,2,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,8,13,24,6,6,2,102,1,27,18,...,0,0,0,0,0,0,0,0,1,0
2,0,0,1,0,0,0,8,0,0,4,...,0,0,0,0,0,0,0,0,0,0
3,0,5,22,0,5,1,51,2,10,1,...,0,0,0,0,0,0,0,0,0,0
4,7,6,17,1,5,2,57,0,9,3,...,0,0,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5167,2,2,2,3,0,0,32,0,0,5,...,0,0,0,0,0,0,0,0,0,0
5168,35,27,11,2,6,5,151,4,3,23,...,0,0,0,0,0,0,0,0,1,0
5169,0,0,1,1,0,0,11,0,0,1,...,0,0,0,0,0,0,0,0,0,0
5170,2,7,1,0,2,1,28,2,0,8,...,0,0,0,0,0,0,0,0,1,0
5171,22,24,5,1,6,5,148,8,2,23,...,0,0,0,0,0,0,0,0,0,0

In [13]:
Y = df.iloc[:,-1].values
Y

array([0, 0, 0, ..., 1, 1, 0])

### **Membuat variabel train dan test**

In [14]:
train_x,test_x,train_y,test_y = train_test_split(X,Y,test_size = 0.25)

### **Perhitungan Naive Bayes**

In [15]:
mnb = MultinomialNB(alpha=1.9)
mnb.fit(train_x,train_y)
y_pred1 = mnb.predict(test_x)
print("Accuracy Score for Naive Bayes : ", accuracy_score(y_pred1,test_y))

Accuracy Score for Naive Bayes :  0.9481825212683681

## **Support Vector Machines**

Support Vector Machines adalah algoritma yang paling dicari untuk masalah klasifikasi klasik. SVMs bekerja pada algoritma Maximal Margin, yaitu, mencari margin atau ambang batas maksimal antara vektor dukungan dari dua kelas (dalam klasifikasi biner). Mesin Vektor Pendukung yang paling efektif adalah kelasifikator margin maksimal lunak, yang memungkinkan satu kesalahan klasifikasi, yaitu, model dimulai dengan bias rendah (performa sedikit buruk) untuk memastikan variansi rendah kemudian.

In [16]:
svc = SVC(C=1.0,kernel='rbf',gamma='auto')
svc.fit(train_x,train_y)
y_pred2 = svc.predict(test_x)
print("Accuracy Score for SVC : ", accuracy_score(y_pred2,test_y))

Accuracy Score for SVC :  0.9203402938901779

*Seperti yang diharapkan, performa SVM sedikit lebih buruk daripada Multinomial Naive Bayes.*

## **Random Forests (Bagging)**
Metode ensemble mengubah model yang lemah menjadi yang sangat kuat. Mari kita lihat apakah model ensemble dapat melakukan lebih baik daripada Naive Bayes.

In [17]:
rfc = RandomForestClassifier(n_estimators=100,criterion='gini')
rfc.fit(train_x,train_y)
y_pred3 = rfc.predict(test_x)
print("Accuracy Score of Random Forest Classifier : ", accuracy_score(y_pred3,test_y))

Accuracy Score of Random Forest Classifier :  0.9729311678267595

*Seperti yang diharapkan, Random Forest Classifier melakukan yang terbaik di antara ketiganya. **Decision tree classifiers** adalah kelasifikator yang sangat baik. **Random forest** adalah model ensemble populer yang menggunakan **forest of decision trees**. Jadi, jelas, menggabungkan akurasi dari 100 trees (seperti n_estimators=100 di sini), akan membuat model yang kuat.*